---
title: "Visualization intro"
format: html
editor: visual
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(janitor)
library(scales)

```

```{r}
#Read in data
escape_raw <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e")
```

```{r}
#Clean names
escape <- escape_raw %>%
  janitor::clean_names()
```

```{r}
annual_esc <- escape %>%
  filter(species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink")) %>%
  mutate(year = lubridate::year(sample_date)) %>%
  group_by(species, sasap_region, year) %>%
  summarise(escapement = sum(daily_count))
```

## Visualization

```{r}
ggplot(annual_esc, aes(x = species, y = escapement)) +
  geom_col()
```

```{r}
annual_esc %>%
  filter(species %in% "Sockeye",
         sasap_region %in% "Bristol Bay") %>%
  ggplot(aes(x= year, y = escapement)) +
  geom_line(color = "red") +
  geom_point()
```

```{r}
annual_esc %>%
  filter(year == 1974,
         species %in% c("Chum", "Pink")) %>%
  ggplot(aes(x=species, y=escapement)) +
  geom_boxplot()
```

```{r}
ggplot(annual_esc,
       aes(x = species, y = escapement,
           fill = sasap_region)) +
    geom_col()
```

```{r}
annual_esc_2000s <- annual_esc %>%
  filter(year %in% 2000:2016)
```

```{r}
ggplot(annual_esc_2000s, aes(x = year,
                             y = escapement,
                             color = species)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(label=comma) +
  facet_wrap( ~ sasap_region,
              scales = "free_y") +
  labs(title = "Annual Salmon escapement by region",
       y = "Escapement", 
       x = "Year")  +
    theme(legend.position = "bottom")
```

## Interactive visualization

## DT

```{r}
library(DT)
```

```{r}
locations <- escape %>%
  distinct(location, latitude, longitude) %>%
  drop_na()
```

```{r}
datatable(locations)
```

## leaflet
```{r}
library(leaflet)

```

```{r}
leaflet(locations) %>%
  addTiles %>%
  addMarkers(
    lng = ~longitude,
    lat = ~latitude,
    popup = ~location
  )
```
```{r}
leaflet(locations) %>%
    addWMSTiles(
        "https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?request=getmap&service=wms&BBOX=-90,-180,90,360&crs=EPSG:4326&format=image/jpeg&layers=gebco_latest&width=1200&height=600&version=1.3.0",
        layers = 'GEBCO_LATEST',
        attribution = "Imagery reproduced from the GEBCO_2022 Grid, WMS 1.3.0 GetMap, www.gebco.net"
    ) %>%
    addCircleMarkers(
        lng = ~ longitude,
        lat = ~ latitude,
        popup = ~ location,
        radius = 5,
        # set fill properties
        fillColor = "salmon",
        fillOpacity = 1,
        # set stroke properties
        stroke = TRUE,
        weight = 0.5,
        color = "white",
        opacity = 1
    )
```








